name: Lint

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  all:
    name: Lint All
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    uses: ./.github/workflows/lint-all.yml
