# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint TOML

on:
  workflow_call:

permissions: {}

jobs:
  lint:
    name: Tombi
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Tombi
        uses: tombi-toml/setup-tombi@e23e1d4c5044e8c51c41ec19a5c607ab5a83cabd # v1.1.7
        with:
          enable-cache: true

      - name: Check formatting and lint
        run: |
          tombi format --check --diff
          tombi lint --error-on-warnings
