name: Lint all files

on:
  workflow_call:

# TODO: merge all linting in this and make bun/go/rust/uv/tf into test/build focused workflows

jobs:
  # TODO: remove, handled by super
  # yaml-skip:
  #   name: YAML skip check
  #   uses: LouisBrunner/.github/.github/workflows/skip-check.yml@main
  #   with:
  #     paths: '["**/*.ya?ml"]'
  # yaml:
  #   name: YAML
  #   needs: yaml-skip
  #   if: ${{ needs.yaml-skip.outputs.should_skip != 'true' }}
  #   uses: LouisBrunner/.github/.github/workflows/lint-yaml.yml@main
  #   with:
  #     path: ${{ fromJSON(inputs.yaml).path || '.' }}
  #     config-data: ${{ fromJSON(inputs.yaml)['config-data'] || '' }}

  # TODO: remove, handled by super
  # markdown-skip:
  #   name: Markdown skip check
  #   uses: LouisBrunner/.github/.github/workflows/skip-check.yml@main
  #   with:
  #     paths: '["**/*.{md,markdown}"]'
  # markdown:
  #   name: Markdown
  #   needs: markdown-skip
  #   if: ${{ needs.markdown-skip.outputs.should_skip != 'true' }}
  #   uses: LouisBrunner/.github/.github/workflows/lint-markdown.yml@main
  #   with:
  #     path: ${{ fromJSON(inputs.markdown).path || '**/*.{md,markdown}' }}
  #     config: ${{ fromJSON(inputs.markdown).config || '' }}

  biome-skip:
    name: Biome skip check
    uses: LouisBrunner/.github/.github/workflows/skip-check.yml@main
    with:
      paths: '["**/*.jsonc?", "**/*.[mc]?[tj]sx?", "**/*.s?[ca]ss", "**/*.html"]'

  # TODO: replace with super after validating if it works for us
  biome:
    name: Biome
    needs: biome-skip
    if: ${{ needs.biome-skip.outputs.should_skip != 'true' }}
    uses: LouisBrunner/.github/.github/workflows/lint-biome.yml@main
    with:
      path: ${{ fromJSON(inputs.biome).path || '.' }}
      version: ${{ fromJSON(inputs.biome).version || '2.5.0' }}

  toml-skip:
    name: TOML skip check
    uses: LouisBrunner/.github/.github/workflows/skip-check.yml@main
    with:
      paths: '["**/*.toml"]'

  toml:
    name: TOML
    needs: toml-skip
    if: ${{ needs.toml-skip.outputs.should_skip != 'true' }}
    uses: LouisBrunner/.github/.github/workflows/lint-toml.yml@main

  sh-skip:
    name: Shell skip check
    uses: LouisBrunner/.github/.github/workflows/skip-check.yml@main
    with:
      paths: '["**/*.sh"]'

  # TODO: super handles it but with wrong files
  sh:
    name: Shell
    needs: sh-skip
    if: ${{ needs.sh-skip.outputs.should_skip != 'true' }}
    uses: LouisBrunner/.github/.github/workflows/lint-sh.yml@main
    with:
      path: ${{ fromJSON(inputs.sh).path || '.' }}
      shfmt-version: ${{ fromJSON(inputs.sh)['shfmt-version'] || '3.13.1' }}
      shellcheck-version: ${{ fromJSON(inputs.sh)['shellcheck-version'] || 'v0.11.0' }}

  docker-skip:
    name: Docker skip check
    uses: LouisBrunner/.github/.github/workflows/skip-check.yml@main
    with:
      paths: '["**/Dockerfile", "**/Dockerfile.*"]'

  docker:
    name: Docker
    needs: docker-skip
    if: ${{ needs.docker-skip.outputs.should_skip != 'true' }}
    uses: LouisBrunner/.github/.github/workflows/lint-docker.yml@main
    with:
      path: ${{ fromJSON(inputs.docker).path || '.' }}
      dockerfmt-version: ${{ fromJSON(inputs.docker)['dockerfmt-version'] || 'v0.5.4' }}
      options: ${{ fromJSON(inputs.docker).options || '--newline -i 2' }}

  super-linter:
    name: Super Linter
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    uses: LouisBrunner/.github/.github/workflows/lint-super.yml@main
