# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint TOML

on:
  workflow_call:
    inputs:
      tombi-version:
        description: "Tombi version to install"
        type: string
        default: "1.5.5"

permissions: {}

jobs:
  lint:
    name: Tombi
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Tombi
        uses: tombi-toml/setup-tombi@0ca8607861bce3508ba79339c7c47acb40a334e1 # v1.5.4
        with:
          version: ${{ inputs.tombi-version }}
          enable-cache: true

      - name: Check formatting and lint
        run: |
          tombi format --check --diff
          tombi lint --error-on-warnings
