name: Lint configs

on:
  workflow_call:
    inputs:
      run-yaml:
        description: "Run yamllint"
        type: boolean
        default: true
      yaml:
        description: "JSON overrides for lint-yaml (keys: path, config-data)"
        type: string
        default: "{}"
      run-biome:
        description: "Run Biome (JSON/HTML/JS/TS/CSS)"
        type: boolean
        default: true
      biome:
        description: "JSON overrides for lint-biome (keys: path, version)"
        type: string
        default: "{}"
      run-toml:
        description: "Run Tombi (requires tombi.toml in repo root)"
        type: boolean
        default: true
      toml:
        description: "JSON overrides for lint-toml (currently no overrides supported)"
        type: string
        default: "{}"
      run-markdown:
        description: "Run markdownlint"
        type: boolean
        default: true
      markdown:
        description: "JSON overrides for lint-markdown (keys: path, config)"
        type: string
        default: "{}"

# TODO: legacy, get rid of when all repos migrated
permissions: {}

jobs:
  all:
    name: All
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    uses: LouisBrunner/.github/.github/workflows/lint-all.yml@main
