# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint TOML

on:
  workflow_call:

permissions: {}

jobs:
  lint:
    name: Tombi
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Tombi
        uses: tombi-toml/setup-tombi@23af0f0e4fcad609f048a37fb312714cd6b07741 # v1.4.0
        with:
          enable-cache: true

      - name: Check formatting and lint
        run: |
          tombi format --check --diff
          tombi lint --error-on-warnings
