name: Update aggregate tags

on:
  workflow_call:

permissions: {}

jobs:
  retag:
    permissions:
      contents: write
    name: Retag
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Calculate short tag name
        id: calculate_short_tag
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          TRUNC_VER=$(echo "$REF_NAME" | cut -d '.' -f 1)
          echo "Short tag: $TRUNC_VER"
          echo "tag=$TRUNC_VER" >> "$GITHUB_OUTPUT"

      - name: Create or update short tag
        uses: rickstaa/action-create-tag@a1c7777fcb2fee4f19b0f283ba888afa11678b72 # v1.7.2
        with:
          force_push_tag: true
          tag: "${{ steps.calculate_short_tag.outputs.tag }}"
          message: "Points to ${{ github.ref_name }}"
